ALTER TABLE users
ADD COLUMN IF NOT EXISTS account_status VARCHAR(20) NOT NULL DEFAULT 'Active',
ADD COLUMN IF NOT EXISTS last_login DATETIME NULL,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS user_addresses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255) NULL,
    city VARCHAR(100) NOT NULL,
    province_region VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(100) NOT NULL DEFAULT 'Philippines',
    address TEXT NOT NULL,
    contact_number VARCHAR(20) NOT NULL,
    is_default VARCHAR(5) NOT NULL DEFAULT 'No',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE user_addresses
ADD COLUMN IF NOT EXISTS full_name VARCHAR(150) NOT NULL AFTER user_id,
ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(255) NOT NULL AFTER full_name,
ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255) NULL AFTER address_line1,
ADD COLUMN IF NOT EXISTS city VARCHAR(100) NOT NULL AFTER address_line2,
ADD COLUMN IF NOT EXISTS province_region VARCHAR(100) NOT NULL AFTER city,
ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20) NOT NULL AFTER province_region,
ADD COLUMN IF NOT EXISTS country VARCHAR(100) NOT NULL DEFAULT 'Philippines' AFTER postal_code;

CREATE TABLE IF NOT EXISTS reorder_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    supplier_name VARCHAR(100) NOT NULL,
    supplier_email VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

UPDATE users
SET account_status='Active'
WHERE account_status IS NULL OR account_status='';
